name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Packages.sln

      - name: Build
        run: dotnet build Packages.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Packages.sln --no-build --configuration Release --verbosity normal
